name: CI

on:
  push:
    branches: [main, develop, 'feature/*', '0*']
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        bun-version: [1.3.0, latest]
        # Windows temporarily excluded due to GitHub Actions infrastructure issues

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run typecheck

      - name: Lint
        run: bun run lint

      - name: Format check
        run: bun run format:check

      - name: Run unit tests
        run: bun run test:unit

      # Coverage disabled temporarily - requires LocalStack for AWS integration tests
      # - name: Generate coverage report
      #   if: matrix.os == 'ubuntu-latest' && matrix.bun-version == 'latest'
      #   run: bun run test:coverage

      # - name: Upload coverage to Codecov
      #   if: matrix.os == 'ubuntu-latest' && matrix.bun-version == 'latest'
      #   uses: codecov/codecov-action@v4
      #   with:
      #     fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run build

      - name: Check build artifacts
        run: |
          test -f dist/index.js
          test -f dist/index.d.ts

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7
