name: CI

on:
  push:
    branches: [main, develop, 'feature/*', '0*']
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        bun-version: [1.3.0, latest]
        # Windows temporarily excluded due to GitHub Actions infrastructure issues

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run typecheck

      - name: Lint
        run: bun run lint

      - name: Format check
        run: bun run format:check

      - name: Run unit tests
        run: bun run test:unit

      # Coverage disabled temporarily - requires LocalStack for AWS integration tests
      # - name: Generate coverage report
      #   if: matrix.os == 'ubuntu-latest' && matrix.bun-version == 'latest'
      #   run: bun run test:coverage

      # - name: Upload coverage to Codecov
      #   if: matrix.os == 'ubuntu-latest' && matrix.bun-version == 'latest'
      #   uses: codecov/codecov-action@v4
      #   with:
      #     fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run build

      - name: Check build artifacts
        run: |
          test -f dist/index.js
          test -f dist/index.d.ts

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7

  integration:
    name: Integration Tests (LocalStack)
    runs-on: ubuntu-latest
    needs: build

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3,dynamodb,sqs,sns,secretsmanager,events
          DEBUG: 0
          EAGER_SERVICE_LOADING: 1
          AWS_REGION: us-east-1
          LOCALSTACK_HOST: localhost:4566
        options: >-
          --health-cmd "curl -f http://localhost:4566/_localstack/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Wait for LocalStack to be ready
        run: |
          echo "Waiting for LocalStack to be ready..."
          max_attempts=60
          attempt=0

          until curl -f http://localhost:4566/_localstack/health >/dev/null 2>&1 && \
                curl -s http://localhost:4566/_localstack/health | grep -q '"services"' || [ $attempt -eq $max_attempts ]; do
            attempt=$((attempt + 1))
            echo "Attempt $attempt/$max_attempts: LocalStack not ready yet..."
            sleep 3
          done

          if [ $attempt -eq $max_attempts ]; then
            echo "LocalStack failed to become ready"
            echo "Health check response:"
            curl -s http://localhost:4566/_localstack/health || echo "Could not reach LocalStack"
            exit 1
          fi

          echo "LocalStack is ready!"
          echo "Health status:"
          curl -s http://localhost:4566/_localstack/health | jq . || curl -s http://localhost:4566/_localstack/health

      - name: Run integration tests (LocalStack-supported services only)
        run: ./scripts/run-localstack-tests.sh
        env:
          AWS_ENDPOINT_URL: http://localhost:4566
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_REGION: us-east-1

      - name: Run contract tests (Mock providers)
        run: bun run test:contract
        env:
          # Contract tests use Mock provider, not LocalStack
          SKIP_AWS_TESTS: true

  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: [build, integration]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@stainedhead'

      - name: Install dependencies
        run: bun install

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
