name: Integration Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    # Only run if AWS credentials are configured
    if: github.event_name == 'workflow_dispatch' || vars.RUN_INTEGRATION_TESTS == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run integration tests
        run: bun run test:integration
        env:
          AWS_REGION: us-east-1
          RUN_INTEGRATION_TESTS: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: coverage/
          retention-days: 30
